### ISSUE TITLE
Rviz crashes when planning by cartesian path

### ISSUE THREAD

**Issue by XHao1997** [UniversalRobots/Universal_Robots_ROS2_Ignition_Simulation#57] opened 2024-10-08 12:14 UTC
![Screenshot from 2024-10-08 20-13-31](https://github.com/user-attachments/assets/63c624fe-33bd-444c-844f-4a7ff9535fb3)
I can't fix it though adding use_sim_time:=true

**Comment by fmauch** [comment] 2024-10-08 18:25
You **can** or you **can't** fix it adding `use_sim_time:=true`? Adding that seems not to be the worst idea, anyway... Where exactly did you (try?) to set it?

**Comment by XHao1997** [comment] 2024-10-09 05:48
I **can't fix**  it by setting use_sim_time. I try setting it in **ur_sim_moveit.launch.py,** unfortunately, it doesn't work. The rviz will crash once it plans by cartesian path. 

    ur_control_launch = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            [FindPackageShare("ur_simulation_gz"), "/launch", "/ur_sim_control.launch.py"]
        ),
        launch_arguments={
            "ur_type": ur_type,
            "safety_limits": safety_limits,
            "runtime_config_package": runtime_config_package,
            "controllers_file": controllers_file,
            "description_package": description_package,
            "description_file": description_file,
            "prefix": prefix,
            "use_sim_time": "true",
            "launch_rviz": "false",
            
        }.items(),
    )

**Comment by fmauch** [comment] 2024-10-09 07:48
Thank you for the elaboration. Th place where you added `use_sim_time` isn't really doing anything, as that is not an input argument of  `ur_sim_control.launch.py` (This wouldn't make sense, since it is a simulation launch file. after all)

I can confirm that this doesn't work and leads to a crash.

I got it somehow working by passing `use_sim_time = true` to the MoveIt rviz instance [here](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/8f2dfa97eee6ce443f5eb43a611f3690e5c7d19e/ur_moveit_config/launch/ur_moveit.launch.py#L177):

```
        parameters=[
            moveit_config.robot_description,
            moveit_config.robot_description_semantic,
            moveit_config.robot_description_kinematics,
            moveit_config.planning_pipelines,
            moveit_config.joint_limits,
            warehouse_ros_config,
            {
                "use_sim_time": use_sim_time,
            },
```

With that, I was able to plan Cartesian paths successfully. However, I cannot query the goal state with the interactive marker as soon as I add that parameter. I'm, not familiar enough with either MoveIt or GZ-Sim to understand what is going wrong here. I noticed that the `/clock` topic doesn't contain any message, though.

I tested the same `use_sim_time` adaption in Humble using Gazebo classic and there it worked correctly and helped avoiding the crash, so this is probably the right way to go.

**Comment by XHao1997** [comment] 2024-10-11 11:07
If I understand correctly, I need to download and modify the source code and then build it. Sorry, I am a beginner in ROS and I am looking forward to your reply~

**Comment by fmauch** [comment] 2024-10-11 11:13
At the moment it's not as simple as that as I described above. We'll probably provide a fix soon.

**Comment by fmauch** [comment] 2024-10-12 12:06
This issue should be fixed (on Rolling) by the following three PRs

- https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/pull/1144
- https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/pull/1145
- https://github.com/UniversalRobots/Universal_Robots_ROS2_GZ_Simulation/pull/58

**Comment by urfeex** [comment] 2024-12-04 11:27
As all mentioned PRs are now merged, I'll close this.

**Closed as completed by urfeex** 2024-12-04 11:27 UTC
Labels: bug
